services:
  - type: web
    name: northstar-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: GRAFANA_OTLP_ENDPOINT
        sync: false
      - key: GRAFANA_OTLP_AUTH
        sync: false
      - key: GRAFANA_API_TOKEN
        sync: false
      - key: GRAFANA_INSTANCE_ID
        value: "1833895"
      - key: GRAFANA_REGION
        value: ap-south-1
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.12"

  - type: web
    name: northstar-generator
    runtime: docker
    rootDir: data-generator
    plan: free
    envVars:
      - key: OTEL_EXPORTER_OTLP_ENDPOINT
        sync: false
      - key: OTEL_EXPORTER_OTLP_AUTH
        sync: false
